### ISSUE TITLE
[1.19.2] Compatible with versions 1.19.X

### ISSUE THREAD

**Issue by kingkuys2123** [Slomaxonical-907/Dustrial-Decor-Fabric#5]
This mod runs perfectly fine in 1.19.2, 
maybe edit and add 1.19.1 and 1.19.2 (and maybe 1.19.3) as supported/compatible versions in the curseforge, 
so it could be added to modpacks? :)

Since in the files it supports latest versions of all required dependencies.

**Comment by Slomaxonical-907** [comment]
cool
