### ISSUE TITLE
The license for the original 'Dustrial Decor is different to the license for this project.

### ISSUE THREAD

**Issue by Cyanide-1** [Slomaxonical-907/Dustrial-Decor-Fabric#8]
The original 'Dustrial Decor is under LGPLv2.1 and not ARR. The licensing for this mod is incorrect. I suggest changing it to match the original mod's license. https://github.com/BlueDuckYT/DustrialDecor/blob/master/LICENSE.txt

As the LGPLv2.1 is a free software copyleft license, all changes made to the codebase must also be under the same license or a compatible one. (aka like MIT, BSD, etc.) Not changing it to the original license means you risk legal trouble and is a ticking time bomb. I am not the original modmaker, so i dont have any copyrights over this project, i am just a concerned user who suggests making this change to fix it.

**Comment by Slomaxonical-907** [comment]
https://www.curseforge.com/minecraft/mc-mods/dustrial-decor i just went with the license mentioned here

**Comment by Cyanide-1** [comment]
> https://www.curseforge.com/minecraft/mc-mods/dustrial-decor i just went with the license mentioned here

The license on the curseforge is incorrect (curseforge defaults to ARR when not specified), the creator told me themselves it is under LGPLv2.1, check the [linked github repo](https://github.com/BlueDuckYT/DustrialDecor) if you need more proof.

**Comment by Slomaxonical-907** [comment]
a bit late but, got the verification from BlueDuck, indeed it's LGPL

**Comment by Cyanide-1** [comment]
nice!
